### ISSUE TITLE
Can you say more in the README as to what this repository is about?

### ISSUE THREAD

**Issue by paul-hammant** [KazuCocoa/flutter-appium#2]
Is this an example of Appium for a Flutter app that other people should be inspired by?

Or is it the illustration of a shortcoming somehow?  The README certainly lists a shortcoming for testability.

**Comment by KazuCocoa** [comment]
I added some explanation, ensure this is experimental, in the README. This repository is an example to use Appium for Flutter.

https://github.com/KazuCocoa/flutter-appium

**Comment by paul-hammant** [comment]
Things to add for "development setup + running the build" section

```
sudo gem install appium_lib_core
npm install -g appium wd
appium & 
```
Next I had to change the iOS SDK version in test.rb (ine 8) to 11.4

Then it all worked:

![iphone_6_-_11_4_and_flutter-appium_ _-bash_ _dtservicehub_ _175x43](https://user-images.githubusercontent.com/82182/41702063-a924d36a-7526-11e8-903c-7333a83f476a.png)

The runner is a bit flakey though. Or maybe there was a "first time" issue that went away for second and subsequent.

**Comment by paul-hammant** [comment]
Observations:

1. The load time for the simulator is pretty long, but you leave that open of course.

2. Running the test suite a second time with the simulator open from the last run , is only slightly faster, with the same version of the app installed again.  Probably for good reason - flushing previous state. Too bad in a way as it makes everything slower.

**Comment by paul-hammant** [comment]
If I comment out the 2 iOS lines, and uncoment the three Andoid lines...

![test_rb_ _flutter-appium__git__master_](https://user-images.githubusercontent.com/82182/41702678-e456902a-7528-11e8-847f-d4c95cfd6ad9.png)

.... I get:

```
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Killing adb server on port 5037
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1529564169689 (07:56:09 GMT+0100 (British Summer Time))
[W3C] Encountered internal error running command: Error: Could not find a connected Android device.
[W3C]     at ADB.getDevices$ (/usr/local/lib/node_modules/appium/node_modules/appium-adb/lib/tools/system-calls.js:188:13)
[W3C]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[W3C]     at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
[W3C]     at new Promise (<anonymous>)
[W3C]     at new F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
[W3C]     at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
[W3C]     at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
[W3C]     at getDevices (/usr/local/lib/node_modules/appium/node_modules/appium-adb/build/lib/tools/system-calls.js:402:38)
[W3C]     at ADB.getDevices$ (/usr/local/lib/node_modules/appium/node_modules/appium-adb/lib/tools/system-calls.js:205:20)
[W3C]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 21574 ms - 1148
UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device.: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device. (Selenium::WebDriver::Error::UnknownError)
	from     at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:806:13)
	from     at asyncHandler$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:361:37)
	from     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
	from     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
	from     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
	from     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
	from /Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
	from /Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
[HTTP] 
	from /Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/http/common.rb:84:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/http/common.rb:84:in `create_response'
	from /Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
	from /Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/http/common.rb:62:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/appium_lib_core-1.7.1/lib/appium_lib_core/common/base/bridge.rb:91:in `create_session'
	from /Library/Ruby/Gems/2.3.0/gems/appium_lib_core-1.7.1/lib/appium_lib_core/common/base/bridge.rb:31:in `handshake'
	from /Library/Ruby/Gems/2.3.0/gems/appium_lib_core-1.7.1/lib/appium_lib_core/common/base/driver.rb:18:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/appium_lib_core-1.7.1/lib/appium_lib_core/driver.rb:178:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/appium_lib_core-1.7.1/lib/appium_lib_core/driver.rb:178:in `start_driver'
	from test.rb:43:in `<main>'
```

I'm not sure how to get past that. Maybe my Android setup is bad, somehow :-(

**Comment by KazuCocoa** [comment]
ah... I see. I'll add how to use section soon.

----

Could you create an emulator with _Android 8.1_ and launch it?
After launching the emulator, you should be able to see below result with `adb devices`.

```
$ adb devices
List of devices attached
emulator-5554	device
```

After it, the 500 error will fix.

**Comment by paul-hammant** [comment]
Thanks!  Will report back.

**Comment by KazuCocoa** [comment]
updated: https://github.com/KazuCocoa/flutter-appium
(README and sort of test code)
